project_id = "urpqjnoowsdehvkrqxmy"

[functions.verify-signing-token]
verify_jwt = false

[functions.send-signing-email]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.send-auto-reminders]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.verify-reset-token]
verify_jwt = false

[functions.auth-email-hook]
verify_jwt = false
