project_id = "urpqjnoowsdehvkrqxmy"

[functions.verify-signing-token]
verify_jwt = false

[functions.send-signing-email]
verify_jwt = false

[functions.send-team-invite]
verify_jwt = false

[functions.send-auto-reminders]
verify_jwt = false
