import { useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Loader2, Download } from "lucide-react";
import { toast } from "sonner";

interface AuditExportButtonProps {
  clientId: string;
  clientName: string;
}

export function AuditExportButton({ clientId, clientName }: AuditExportButtonProps) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    try {
      // Fetch all documents for this client
      const { data: documents, error: docsError } = await supabase
        .from("documents")
        .select("id, file_name, file_type, file_size_bytes, storage_path, created_at")
        .eq("client_id", clientId)
        .order("created_at", { ascending: true });

      if (docsError) throw docsError;

      // Fetch all tasks
      const { data: tasks, error: tasksError } = await supabase
        .from("tasks")
        .select("id, title, description, status, priority, due_date, created_at, updated_at")
        .eq("client_id", clientId)
        .order("created_at", { ascending: true });

      if (tasksError) throw tasksError;

      // Build the manifest
      const now = new Date();
      const manifest = [
        `AUDIT-READY EXPORT — ${clientName}`,
        `Generated: ${now.toLocaleString()}`,
        `Client ID: ${clientId}`,
        ``,
        `═══════════════════════════════════════`,
        `DOCUMENT INVENTORY (${documents?.length || 0} files)`,
        `═══════════════════════════════════════`,
        ``,
      ];

      let totalSize = 0;
      documents?.forEach((doc, i) => {
        const size = doc.file_size_bytes || 0;
        totalSize += size;
        manifest.push(
          `${(i + 1).toString().padStart(3, " ")}. ${doc.file_name}`,
          `     Type: ${doc.file_type || "unknown"}`,
          `     Size: ${size ? `${(size / 1024).toFixed(1)} KB` : "unknown"}`,
          `     Uploaded: ${new Date(doc.created_at).toLocaleString()}`,
          `     Storage Path: ${doc.storage_path}`,
          ``
        );
      });

      manifest.push(
        `Total Documents: ${documents?.length || 0}`,
        `Total Size: ${(totalSize / (1024 * 1024)).toFixed(2)} MB`,
        ``,
        `═══════════════════════════════════════`,
        `TASK ACTIVITY LOG (${tasks?.length || 0} tasks)`,
        `═══════════════════════════════════════`,
        ``
      );

      tasks?.forEach((task, i) => {
        manifest.push(
          `${(i + 1).toString().padStart(3, " ")}. ${task.title}`,
          `     Status: ${task.status.toUpperCase()}`,
          `     Priority: ${task.priority}`,
          task.description ? `     Description: ${task.description}` : "",
          task.due_date ? `     Due Date: ${new Date(task.due_date).toLocaleDateString()}` : "",
          `     Created: ${new Date(task.created_at).toLocaleString()}`,
          `     Last Updated: ${new Date(task.updated_at).toLocaleString()}`,
          ``
        );
      });

      const completedTasks = tasks?.filter((t) => t.status === "completed") || [];
      const pendingTasks = tasks?.filter((t) => t.status === "pending") || [];
      const inProgressTasks = tasks?.filter((t) => t.status === "in_progress") || [];

      manifest.push(
        `═══════════════════════════════════════`,
        `SUMMARY`,
        `═══════════════════════════════════════`,
        ``,
        `Tasks Completed: ${completedTasks.length}/${tasks?.length || 0}`,
        `Tasks Pending: ${pendingTasks.length}`,
        `Tasks In Progress: ${inProgressTasks.length}`,
        `Documents Collected: ${documents?.length || 0}`,
        ``,
        `--- End of Audit Export ---`,
        `Generated by LedgerStash — ledgerstash.com`
      );

      // Download as text file
      const content = manifest.filter((l) => l !== undefined).join("\n");
      const blob = new Blob([content], { type: "text/plain;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const link = document.createElement("a");
      const safeName = clientName.replace(/[^a-zA-Z0-9]/g, "_");
      link.href = url;
      link.download = `${safeName}_Audit_Export_${now.toISOString().split("T")[0]}.txt`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);

      toast.success("Audit export downloaded");
    } catch (error: any) {
      console.error("Export error:", error);
      toast.error(error.message || "Failed to generate export");
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button variant="outline" size="sm" onClick={handleExport} disabled={exporting}>
      {exporting ? (
        <><Loader2 className="h-4 w-4 animate-spin" /> Exporting...</>
      ) : (
        <><Download className="h-4 w-4" /> Audit Export</>
      )}
    </Button>
  );
}
